toc = true
avatar = "https://2.gravatar.com/avatar/0ccdec5c65411080241ed437de00b897962f2ba29f4b81f4ede8383ccebb1482?size=512"
author = "Bastiaan"

[assets]
  self_host = false

[social]
  name = "Bastiaan Quast"
  url = "https://github.com/bquast"

[[social.links]]
  type = "github"
  id = "bquast"
  icon = "fab fa-github"

[[social.links]]
  type = "twitter"
  id = "baquast"
  icon = "fab fa-x-twitter"

[[social.links]]
  type = "custom"
  id = "https://en.wikipedia.org/wiki/Bastiaan_Quast"
  icon = "fab fa-wikipedia-w"

[[social.links]]
  type = "custom"
  id = "https://grokipedia.com/page/bastiaan_quast"
  icon = "fa-solid fa-planet-ringed"
  noblank = false

[comments]
  enable = false
  provider = ""
